version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        cargo watch -x run
      "
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    environment:
      DATABASE_URL: mysql://user:password@db:3306/actix_db?connect_timeout=60
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: actix_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
  cargo-cache:
  target-cache:
